config/routes.rb
Rails.application.routes.draw do
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"

  get '/register', to: "users#new"
  resources 'users'
  get '/dashboard', to: "users#show", as: "dashboard"

  get "/location", to: "location#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name

  validates :email, uniqueness: true

  has_secure_password validations: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController

  def show
    @facade = LocationFacade.new(params[:search])
  end

  # private
  # def user_params
  #   params.require(:user).permit(:email, :name, :password, :password_confirmation)
  # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in as #{user.name}"
      redirect_to dashboard_path
    else
      flash[:error] = "Looks like your email or password is invalid"
      redirect_to login_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if user_params[:password] == user_params[:password_confirmation]
      user = User.create(user_params)
      if user.save
        session[:user_id] = user.id
        flash[:notice] = "Registered as #{user.name}"
        redirect_to dashboard_path
      else
        flash[:notice] = "A account already exist with that email"
        redirect_to dashboard_path
      end
    else
      flash[:notice] = "Passwords did not match"
      redirect_to dashboard_path
    end
  end

  def show
  end

  private
  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoveTime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/location/show.html.erb
<%= @facade.county %>

app/views/users/new.html.erb
<%= form_for @user do |form| %>
    <%= form.label :email %>
    <%= form.email_field :email %>
  <br>
    <%= form.label :name %>
    <%= form.text_field :name %>
  <br>
    <%= form.label :password %>
    <%= form.password_field :password %>
  <br>
    <%= form.label :Confirm_password %>
    <%= form.password_field :password_confirmation %>
  <br>
    <%= form.submit 'Register', class: 'btn btn-primary' %>
<% end %>

app/views/users/show.html.erb
<%= form_tag(location_path, method: :get) do %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag("Search") %>
<% end %>